import './globals.css'
import Header from '../components/Header';
import { Righteous } from 'next/font/google';

const righteous = Righteous({
  subsets: ['latin'],
  weight: ['400', ],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={righteous.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
